# Generated by Django 4.1 on 2022-09-02 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_words', '0010_alter_word_saved_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='send_times',
            field=models.ManyToManyField(default=None, null=True, to='daily_words.sendtime'),
        ),
    ]
