# Generated by Django 4.1 on 2022-09-02 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_words', '0011_sendtime_user_send_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtime',
            name='hour',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
