# Generated by Django 4.1 on 2022-09-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_words', '0013_alter_sendtime_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='send_times',
            field=models.ManyToManyField(to='daily_words.sendtime'),
        ),
    ]
