# Generated by Django 4.1 on 2022-09-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_words', '0014_alter_user_send_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='saved_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
